### ISSUE TITLE
How does the sync flow work for an existing vault?

### ISSUE THREAD

**Issue by f0ff886f** [acheong08/rev-obsidian-sync-plugin#1]
Hi, one thing is a bit unclear from the docs.

Let's say I start off with a fresh instance of rev-obsidian-sync server. I sign up somehow (I saw endpoints in the sync server).

I go to an Obsidian installation, add this plugin.

Then I can signup, and I can sync my vault, and lets say I make 3-4 docs.

Then I want to enable sync on another device. It says I should add the plugin to a vault, but my vault from rev-obsidian-sync is still not on the new device. So I make an empty vault? Add the plugin there? Then I can sign in and pull down my existing vault?

That's the part I'm confused about, how do you sync an existing vault to a new device considering that you need to create a vault on the existing device in order to install the plugin...

Thanks for the hard work on this! I'm getting big Vaultwarden vibes which is an awesome project to enable official clients with self-hosted infra. One thing, the CEO on HN did mention you should not call your service "Obsidian Sync" due to the trademark they have... 

You probably want to change that soon to something very different (Revsidian Server or something silly that isn't similar to Sync in any form).

**Comment by acheong08** [comment]
> That's the part I'm confused about, how do you sync an existing vault to a new device considering that you need to create a vault on the existing device in order to install the plugin...

Create new vault, install the plugin for the vault, enable sync, connect to original remote vault

**Comment by acheong08** [comment]
> One thing, the CEO on HN did mention you should not call your service "Obsidian Sync" due to the trademark they have...

Although I cannot call it `obsidian-sync` directly, `rev-obsidian-sync` is legally allowed as it makes clear that it is not from the official source. It is also clearly stated in the readme that it is not official.

Based on my experience with https://github.com/acheong08/ChatGPT, as long a clear enough distinction is made, they cannot legally touch you. I am still open to renaming it to something more creative if I can think of a nice name

**Comment by acheong08** [comment]
> That's the part I'm confused about, how do you sync an existing vault to a new device considering that you need to create a vault on the existing device in order to install the plugin...

There is a distinction between your local vault & the remote vault. A remote vault can be synced to ∞ local vaults
