### ISSUE TITLE
Not working on 1.5.3?

### ISSUE THREAD

**Issue by blackshot** [acheong08/rev-obsidian-sync-plugin#10]
As the title says i just mounted the server, registered an new user but plugin doesn't seems to work
![image](https://github.com/acheong08/rev-obsidian-sync-plugin/assets/3688208/45e542c4-de8b-44ab-9fb1-a58b141ce952)
any workarounds?

**Comment by acheong08** [comment]
> The plugin is broken on obsidian >= 1.4.11. This is intentional by the official ObsidianMD team. They have made clear their dissatisfaction with this project. 

I forgot to archive this repository
