### ISSUE TITLE
WebSocket URL is wrongly determined

### ISSUE THREAD

**Issue by lukstei** [acheong08/rev-obsidian-sync-plugin#2]
Hi,

Thanks for this awesome plugin.

I had one issue when setting up the sync though. When determining the WS URL by calling the `origGetHost` function, in https://github.com/acheong08/rev-obsidian-sync-plugin/blob/d55ae0eeb1256b9739cdc71dc3d75a10d6787b80/main.ts#L79 on my side it is set to `localhost:3000`, which is the wrong URL (not sure about why this URL is retrieved from the original plugin in this case?)
When setting the WS URL to the host from `this.settings.SyncAPI` the syncing works :-)

I'll send a PR with the fix!

**Comment by acheong08** [comment]
Thank you!
