### ISSUE TITLE
Any instruction for use this plugin in a mobile device?

### ISSUE THREAD

**Issue by ZacharyJia** [acheong08/rev-obsidian-sync-plugin#5]
For example if I have setup a vault in a PC, then how can I sync it to my mobile obsidian?

**Comment by acheong08** [comment]
You need a server. Run github.com/acheong08/obsidian-sync on there and set the API endpoint as the IP or domain name for both your PC and mobile

**Comment by ZacharyJia** [comment]
I have already run a server and setup a vault synced to this server, but how can i use this plugin to change the sync URL in a mobile device? It seems hard to access the .obsidian folder in mobile devices.

**Comment by ZacharyJia** [comment]
>  # I can't find the .obsidian directory
> It's hidden. You can configure your file app to show hidden files or use a terminal. For IOS, you might need to plug it into a computer, go to "Documents on iPhone", then Obsidian/<your vault name>/.obsidian. Then follow the installation instructions.

Just noticed the description in the readme. Sorry about this issue, will close it.
