### ISSUE TITLE
Manifest version out of date with release tags

### ISSUE THREAD

**Issue by f0ff886f** [acheong08/rev-obsidian-sync-plugin#7]
The manifest version in the manifest.json is `1.0.4` while the latest release is `1.1.0`.

I found this out because it turns out https://tfthacker.com/Obsidian+Plugins+by+TfTHacker/BRAT+-+Beta+Reviewer's+Auto-update+Tool/Working+with+Plugins will install the plugin based on `manifest.json` contents.

This tool by the way, BRAT, makes installing this plugin trivial on iOS / Android, you never have to touch the file system. Simply install the BRAT community plugin (official sources) and then paste the URL of the repo into it, and it downloads the plugin release automatically to the file system.

**Comment by acheong08** [comment]
https://github.com/acheong08/rev-obsidian-sync-plugin/releases/tag/1.1.1

**Comment by f0ff886f** [comment]
Thank you! One odd thing is that this plugin (I thought was caused by the manifest) is not showing any settings on iOS. It works fine on Linux, but not iOS. I tried to manually pull down the main.js / manifest.json straight from the repo, but it didn't work still.

BRAT is very useful to install btw, if things get working 100% I can submit a PR to the README :)

**Comment by acheong08** [comment]
Some conversation regarding IOS:

https://github.com/acheong08/rev-obsidian-sync-plugin/commit/d2159c25f3b28660393c5dba2db7f54641b667bc

**Comment by acheong08** [comment]
The main issue on IOS is the complete lack of dev tools. It's quite difficult to figure out where the `electronWindow` is. If anyone has XCode & IOS simulator, perhaps it would be easier.
