### ISSUE TITLE
Compatibility with iOS v1.4.8

### ISSUE THREAD

**Issue by oskardotglobal** [acheong08/rev-obsidian-sync-plugin#8]
Can't seem to get this to work with the latest iOS version released 6 days ago.
The URL doesn't seem to change, I can log into sync with an official account but not with my self-hosted credentials.

I get the following message on start:
> Failed to intercept requests.
> The error was: TypeError: undefined is not an object (evaluating
'window.electronWindow.webContents')

Patch notes for 1.4.8:
- Includes all new functionality and bug fixes up to Obsidian Desktop v1.3.7.
- Added support for 2FA login.
- PDF: Fixed text selection.
- Sync: Improved sync UI. Added loading state to sync modal.

**Comment by acheong08** [comment]
Some discussion here: https://github.com/acheong08/rev-obsidian-sync-plugin/commit/d2159c25f3b28660393c5dba2db7f54641b667bc

TL;DR: Obsidian 1.4.x patched how the plugin used to work.

> What we did in the update is to prevent plugins from taking over the account system and pretending to be the official Obsidian account, and official Obsidian Sync client. It is indeed a security vulnerability that we felt necessary to address.

@t3chguy was able to fix it for Desktop via the electron API which is not available on IOS. I tried to use service workers but an unknown issue causes a crash without error logs.

If you have any ideas on how to intercept & modify fetch requests, feel free to comment

**Comment by oskardotglobal** [comment]
I'll look into it

**Comment by wangweitung** [comment]
Android error

![Screenshot_2023-09-09-07-22-21-213_md obsidian](https://github.com/acheong08/rev-obsidian-sync-plugin/assets/8080125/3d2e8eca-f779-4f1f-bfef-9a6d14a1ba20)

**Comment by itsjuoum** [comment]
Given that 187d051 indicates this was a deliberate patch implemented by the Obsidian devs, should we continue our efforts to find a solution, or would it be deemed 'unethical' to do so?

**Comment by oskardotglobal** [comment]
I see no reason not to, that's just reverse engineering for ya

**Comment by oskardotglobal** [comment]
See https://github.com/acheong08/obi-sync/issues/29
