### ISSUE TITLE
Failed to intercept requests - Android 14 beta

### ISSUE THREAD

**Issue by azoller1** [acheong08/rev-obsidian-sync-plugin#9]
Got the obi sync server running ok and is working great with my pc and laptop, but is not working on my phone. Assuming this is a conflict with the plugin and not the server component. Here is a screenshot. I am on the Android 14 beta program so I am assuming it is some compatibility issue perhaps. Wondering if you have some insight.
![Screenshot_20230909-124925](https://github.com/acheong08/rev-obsidian-sync-plugin/assets/2552829/152712cd-285e-4c2e-891d-794868c1df40)

**Comment by acheong08** [comment]
Duplicate of #8

Mobile won't work after 1.4.x. They intentionally stopped it from working by making a copy of window.fetch before any plugins are loaded

**Comment by azoller1** [comment]
Oh ok, did not see that comment. Good to know. This can be closed for now.
